### ISSUE TITLE
Создать скрипты для БД

### ISSUE THREAD

**Issue by Garthdex** [study-eCommece/eCommerce#5]
в папке resources/DBscripts

**Comment by hero2295** [comment]
Скрипты. Сначала запускать creation.sql, а затем filling.sql. Возможно потребуется прописать имя БД в начале каждого из скриптов перед использованием. 


[Scripts.zip](https://github.com/study-eCommece/eCommerce/files/1463828/Scripts.zip)

**Comment by Garthdex** [comment]
и зачем мне твой зип? ты название и описание самого тикета читал? 
"Возможно потребуется прописать имя БД в начале каждого из скриптов перед использованием" И что это за предупреждение о возможной недоработке? Доработать! Никто ничего дописывать не должен.
