### ISSUE TITLE
Реализовать компонент категория(колонка слева и хедер) и наполнение товарами самих категорий

### ISSUE THREAD

**Issue by Garthdex** [study-eCommece/eCommerce#7]
Всю нужную информацию смотрим в техническом дизайне.

**Comment by BloodyShooter** [comment]
сверху на каждой странице располагаются родительские категории
когда нажимаешь на одну из них попадаешь на страницу категории
слева список всех дочерних категорий
посередине список всех товаров попадающих под эту родительскую категорию
справа фильтры(их пока не надо делать)
когда ты нажимаешь на одну из дочерних категорий слева - обновляется страница и рисуются товары по центру именно из этой дочерней категории(если есть желание сделать сразу нормально - придется хуярить js'ом обновление блока с товарами так же асинхронно)
выводится будет по 6 товаров на странице и с низу будет навигация по страницам что бы дальше смотреть их по 6
3 товара в один ряд(пока что так, потом возможно изменим)
т.е. если всего товаров будет 13-18 - то получится 3 страницы в навигации

**Comment by BloodyShooter** [comment]
Антон Кузьмин 21:41
навигацию по страницам можешь пока не трогать, но если будешь трогать - это круто. Семену нужно быстрей сверстать страницу с категориями потому что Егор её активно делает щас
ах да, на странице еще сортировка сверху должна быть, её тоже пока можно не трогать(но повторюсь, если будешь трогать все таки - будет круто :D)
вообще ладно, не трогай ничего лишнего. На них надо отдельные тикеты заводить по-хорошему
